export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PLAN = 'UPDATE_PLAN';

export const UPDATE_TRADE = "UPDATE_TRADE";
export const CREATE_TRADE = "CREATE_TRADE";
export const CREATE_TRADE_SUCCESS = "CREATE_TRADE_SUCCESS";
export const CREATE_TRADE_FAIL = "CREATE_TRADE_FAIL";
export const GET_TRADES = "GET_TRADES";
export const DELETE_TRADE_SUCCESS = "DELETE_TRADE_SUCCESS";
export const DELETE_TRADE_FAIL = "DELETE_TRADE_FAIL";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const EDIT_TRADE_SUCCESS = "EDIT_TRADE_SUCCESS";
export const EDIT_TRADE_FAIL = "EDIT_TRADE_FAIL";
export const OPEN_MODAL_EDIT = "OPEN_MODAL_EDIT";

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const FILTER_TABLE = 'FILTER_TABLE';

export const CREATE_STRATEGY = "CREATE_STRATEGY";
export const UPDATE_STRATEGY = "UPDATE_STRATEGY";
export const GET_STRATEGY_DATA = "GET_STRATEGY_DATA";



export const PAY_NOW = 'PAY_NOW'